### ISSUE TITLE
Static files are not downloaded when installing from git

### ISSUE THREAD

**Issue by Spredzy** [ansible/galaxy_ng#216]
##### SUMMARY

When running the `pulp/pulp_installer` with 

```
 pulp_install_plugins:
      pulp-ansible: {}
      galaxy-ng:
        source_dir: "git+https://github.com/ansible/galaxy_ng.git@master#egg=galaxy-ng"
      pulp-container: {}
```

Deployment goes fine but trying to lo in Automation Hub ends up in Resource Not Found, due to static file not being collected.

##### STEPS TO REPRODUCE

  1. Clone `pulp/pulp_installer`
  2. Specify `galaxy_ng: source-dir: git+https://github.com/ansible/galaxy_ng.git@master#egg=galaxy-ng`
  3. Run installer

##### EXPECTED RESULTS

  * Login page is presented

##### ACTUAL RESULTS

  * HTTP 404
