### ISSUE TITLE
Add automated FQN (fully qualified name) documentation 

### ISSUE THREAD

**Issue by IPvSean** [ansible/galaxy_ng#88]
Right now vendors are responsible for their documentation and they may not use a fully qualified name for their module which can confuse users.  For example the CyberArk collection has this as their example->
```
- name: Logon - use_shared_logon_authentication
  cyberark_authentication:
    api_base_url: "{{ web_services_base_url }}"
    use_shared_logon_authentication: yes
```

This will only work if they are using the `collections` keyword in their Ansible Playbook.  It is recommended to also show the FQN going forward.

```
- name: Logon - use_shared_logon_authentication
  cyberark.pas.cyberark_authentication:
    api_base_url: "{{ web_services_base_url }}"
    use_shared_logon_authentication: yes
```

It is easy to derive the namespace.collection from Ansible Galaxy or Automation Hub

![image](https://user-images.githubusercontent.com/6537680/79469561-54262d00-7fce-11ea-8e33-2a22de051114.png)

However we can go further and just automate this into the UI.  Add something like

This collection FQN (fully qualified name) is ```cyberark.pas``` For example, to use a module in this Ansible Collection please ```cyberark.pas.MODULE_NAME```

ideally you could even choose one module automatically from their repo and do like this->

This collection FQN (fully qualified name) is ```cyberark.pas``` For example, to use a module in this Ansible Collection please ```cyberark.pas.cyberark_authentication```
